# 1. Turn on H2 Web Console                                
    spring.h2.console.enabled=true                             
    spring.h2.console.path=/h2-console                         
                                                               
# 2. Database Connection                                   
    spring.datasource.url=jdbc:h2:mem:discreetdb                      
    spring.datasource.username=sa                              
    spring.datasource.password=                                
                                                               
# 3. Print SQL queries in terminal                         
    spring.jpa.show-sql=true                                   
    spring.jpa.hibernate.ddl-auto=update 